In [11]:
import cv2
path = 'mats/pedestrian/pedestrian/input'
for i in range (300 ,1100) :
  I=cv2.imread ( f'{path}/in%06d.jpg ' % i )
  cv2.imshow ( " I " ,I )
  cv2.waitKey(10)
  print ( " i = " ,i )

cv2.destroyAllWindows()

 i =  300
 i =  301
 i =  302
 i =  303
 i =  304
 i =  305
 i =  306
 i =  307
 i =  308
 i =  309
 i =  310
 i =  311
 i =  312
 i =  313
 i =  314
 i =  315
 i =  316
 i =  317
 i =  318
 i =  319
 i =  320
 i =  321
 i =  322
 i =  323
 i =  324
 i =  325
 i =  326
 i =  327
 i =  328
 i =  329
 i =  330
 i =  331
 i =  332
 i =  333
 i =  334
 i =  335
 i =  336
 i =  337
 i =  338
 i =  339
 i =  340
 i =  341
 i =  342
 i =  343
 i =  344
 i =  345
 i =  346
 i =  347
 i =  348
 i =  349
 i =  350
 i =  351
 i =  352
 i =  353
 i =  354
 i =  355
 i =  356
 i =  357
 i =  358
 i =  359
 i =  360
 i =  361
 i =  362
 i =  363
 i =  364
 i =  365
 i =  366
 i =  367
 i =  368
 i =  369
 i =  370
 i =  371
 i =  372
 i =  373
 i =  374
 i =  375
 i =  376
 i =  377
 i =  378
 i =  379
 i =  380
 i =  381
 i =  382
 i =  383
 i =  384
 i =  385
 i =  386
 i =  387
 i =  388
 i =  389
 i =  390
 i =  391
 i =  392
 i =  393
 i =  394
 i =  395
 i =  396
 i =  397
 i =  398
 i =  399


In [9]:
# Substract the frames
import cv2
path = 'mats/pedestrian/pedestrian/input'

prev_frame = cv2.cvtColor(cv2.imread ( f'{path}/in000300.jpg ' ), cv2.COLOR_BGR2GRAY)

for i in range (300 ,1100,2):
  I=cv2.imread ( f'{path}/in%06d.jpg ' % i )
  gray = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)
  diff = cv2.absdiff(gray, prev_frame)
  cv2.imshow ( " diff " ,diff )
  cv2.waitKey(10)
  print ( " i = " ,i )
  prev_frame = gray

cv2.destroyAllWindows()

 i =  300
 i =  302
 i =  304
 i =  306
 i =  308
 i =  310
 i =  312
 i =  314
 i =  316
 i =  318
 i =  320
 i =  322
 i =  324
 i =  326
 i =  328
 i =  330
 i =  332
 i =  334
 i =  336
 i =  338
 i =  340
 i =  342
 i =  344
 i =  346
 i =  348
 i =  350
 i =  352
 i =  354
 i =  356
 i =  358
 i =  360
 i =  362
 i =  364
 i =  366
 i =  368
 i =  370
 i =  372
 i =  374
 i =  376
 i =  378
 i =  380
 i =  382
 i =  384
 i =  386
 i =  388
 i =  390
 i =  392
 i =  394
 i =  396
 i =  398
 i =  400
 i =  402
 i =  404
 i =  406
 i =  408
 i =  410
 i =  412
 i =  414
 i =  416
 i =  418
 i =  420
 i =  422
 i =  424
 i =  426
 i =  428
 i =  430
 i =  432
 i =  434
 i =  436
 i =  438
 i =  440
 i =  442
 i =  444
 i =  446
 i =  448
 i =  450
 i =  452
 i =  454
 i =  456
 i =  458
 i =  460
 i =  462
 i =  464
 i =  466
 i =  468
 i =  470
 i =  472
 i =  474
 i =  476
 i =  478
 i =  480
 i =  482
 i =  484
 i =  486
 i =  488
 i =  490
 i =  492
 i =  494
 i =  496
 i =  498


In [10]:
# binarize the difference

import cv2
path = 'mats/pedestrian/pedestrian/input'

prev_frame = cv2.cvtColor(cv2.imread ( f'{path}/in000300.jpg ' ), cv2.COLOR_BGR2GRAY)

for i in range (300 ,1100,2):
  I=cv2.imread ( f'{path}/in%06d.jpg ' % i )
  gray = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)
  diff = cv2.absdiff(gray, prev_frame)
  T,binarized = cv2.threshold(diff, 40, 255, cv2.THRESH_BINARY)
  cv2.imshow ( " binarized " ,binarized )
  cv2.waitKey(10)
  print ( " i = " ,i,"\n",_ )
  prev_frame = gray
  
cv2.destroyAllWindows()

 i =  300 
 
 i =  302 
 
 i =  304 
 
 i =  306 
 
 i =  308 
 
 i =  310 
 
 i =  312 
 
 i =  314 
 
 i =  316 
 
 i =  318 
 
 i =  320 
 
 i =  322 
 
 i =  324 
 
 i =  326 
 
 i =  328 
 
 i =  330 
 
 i =  332 
 
 i =  334 
 
 i =  336 
 
 i =  338 
 
 i =  340 
 
 i =  342 
 
 i =  344 
 
 i =  346 
 
 i =  348 
 
 i =  350 
 
 i =  352 
 
 i =  354 
 
 i =  356 
 
 i =  358 
 
 i =  360 
 
 i =  362 
 
 i =  364 
 
 i =  366 
 
 i =  368 
 
 i =  370 
 
 i =  372 
 
 i =  374 
 
 i =  376 
 
 i =  378 
 
 i =  380 
 
 i =  382 
 
 i =  384 
 
 i =  386 
 
 i =  388 
 
 i =  390 
 
 i =  392 
 
 i =  394 
 
 i =  396 
 
 i =  398 
 
 i =  400 
 
 i =  402 
 
 i =  404 
 
 i =  406 
 
 i =  408 
 
 i =  410 
 
 i =  412 
 
 i =  414 
 
 i =  416 
 
 i =  418 
 
 i =  420 
 
 i =  422 
 
 i =  424 
 
 i =  426 
 
 i =  428 
 
 i =  430 
 
 i =  432 
 
 i =  434 
 
 i =  436 
 
 i =  438 
 
 i =  440 
 
 i =  442 
 
 i =  444 
 
 i =  446 
 
 i =  448 
 
 i =  450 
 
 i =  452 
 

In [23]:
# on binarized image, perform median filtration, then erosion and dilation

import cv2
path = 'mats/pedestrian/pedestrian/input'

prev_frame = cv2.cvtColor(cv2.imread ( f'{path}/in000300.jpg ' ), cv2.COLOR_BGR2GRAY)

for i in range (300 ,1100,2):
  I=cv2.imread ( f'{path}/in%06d.jpg ' % i )
  gray = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)
  diff = cv2.absdiff(gray, prev_frame)
  T,binarized = cv2.threshold(diff, 25, 255, cv2.THRESH_BINARY)
  
  median = cv2.medianBlur(binarized, 5)
  kernel_1 = cv2.getStructuringElement(cv2.MORPH_RECT, (3,3))
  kernel_2 = cv2.getStructuringElement(cv2.MORPH_RECT, (2,2))

  eroded = cv2.erode(median, kernel_1, iterations=1)
  dilated = cv2.dilate(eroded, kernel_1, iterations=1)

  for _ in range(4):
    dilated = cv2.dilate(dilated, kernel_2, iterations=1)
    eroded = cv2.erode(dilated, kernel_2, iterations=1)


  cv2.imshow ( " dilated " ,eroded )
  cv2.waitKey(10)
  # print ( " i = " ,i,"\n",_ )
  prev_frame = gray
  
cv2.destroyAllWindows()

 i =  300 
 3
 i =  302 
 3
 i =  304 
 3
 i =  306 
 3
 i =  308 
 3
 i =  310 
 3
 i =  312 
 3
 i =  314 
 3
 i =  316 
 3
 i =  318 
 3
 i =  320 
 3
 i =  322 
 3
 i =  324 
 3
 i =  326 
 3
 i =  328 
 3
 i =  330 
 3
 i =  332 
 3
 i =  334 
 3
 i =  336 
 3
 i =  338 
 3
 i =  340 
 3
 i =  342 
 3
 i =  344 
 3
 i =  346 
 3
 i =  348 
 3
 i =  350 
 3
 i =  352 
 3
 i =  354 
 3
 i =  356 
 3
 i =  358 
 3
 i =  360 
 3
 i =  362 
 3
 i =  364 
 3
 i =  366 
 3
 i =  368 
 3
 i =  370 
 3
 i =  372 
 3
 i =  374 
 3
 i =  376 
 3
 i =  378 
 3
 i =  380 
 3
 i =  382 
 3
 i =  384 
 3
 i =  386 
 3
 i =  388 
 3
 i =  390 
 3
 i =  392 
 3
 i =  394 
 3
 i =  396 
 3
 i =  398 
 3
 i =  400 
 3
 i =  402 
 3
 i =  404 
 3
 i =  406 
 3
 i =  408 
 3
 i =  410 
 3
 i =  412 
 3
 i =  414 
 3
 i =  416 
 3
 i =  418 
 3
 i =  420 
 3
 i =  422 
 3
 i =  424 
 3
 i =  426 
 3
 i =  428 
 3
 i =  430 
 3
 i =  432 
 3
 i =  434 
 3
 i =  436 
 3
 i =  438 
 3
 i =  440 
 3
 i =  

In [24]:
# Indexation and analysis
import cv2
import numpy as np
path = 'mats/pedestrian/pedestrian/input'

prev_frame = cv2.cvtColor(cv2.imread ( f'{path}/in000300.jpg ' ), cv2.COLOR_BGR2GRAY)

for i in range (300 ,1100):
  I=cv2.imread ( f'{path}/in%06d.jpg ' % i )
  gray = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)
  diff = cv2.absdiff(gray, prev_frame)
  T,binarized = cv2.threshold(diff, 10, 255, cv2.THRESH_BINARY)
  
  median = cv2.medianBlur(binarized, 5)
  kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (2,2))

  eroded = cv2.erode(median, kernel, iterations=1)
  dilated = cv2.dilate(eroded, kernel, iterations=1)

  retval , labels , stats , centroids = cv2.connectedComponentsWithStats(dilated)

  # cv2.imshow ( " dilated " ,np.uint8(labels * 255 / retval) )

  I_VIS = I.copy()
  if(stats.shape[0]>1):
    tab = stats[1:,4]
    pi = np.argmax(tab)
    print(f'max area = {tab[pi]}')

    if (tab[pi]>500):
      pi = pi + 1
      cv2.rectangle(I_VIS, (stats[pi,0],stats[pi,1]), (stats[pi,0]+stats[pi,2],stats[pi,1]+stats[pi,3]), (255,0,0), 2)
      cv2.putText(I_VIS, "%f" %stats[pi,4],(stats[pi,0],stats[pi,1]),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,0,0))


    # cv2.putText(I_VIS, "%f" %stats[pi,4],(stats[pi,0],stats[pi,1]),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,0,0))
    # cv2.putText ( I_VIS, "%d " %pi ,( int(centroids[pi,0]) , int(centroids[pi,1]) ) , cv2.FONT_HERSHEY_SIMPLEX ,1 ,(255 ,0 ,0) )


  cv2.imshow ( " I_VIS " ,I_VIS )







  cv2.waitKey(10)
  # print ( " i = " ,i,"\n",_ )
  prev_frame = gray
  
cv2.destroyAllWindows()

max area = 12
max area = 15
max area = 32
max area = 36
max area = 118
max area = 347
max area = 825
max area = 1076
max area = 1172
max area = 1312
max area = 1347
max area = 1539
max area = 1665
max area = 1817
max area = 1830
max area = 1796
max area = 1689
max area = 1486
max area = 1590
max area = 1290
max area = 1488
max area = 1538
max area = 1788
max area = 1916
max area = 1845
max area = 1851
max area = 1863
max area = 2034
max area = 2051
max area = 1959
max area = 1854
max area = 1779
max area = 1613
max area = 1611
max area = 1625
max area = 1685
max area = 1734
max area = 1873
max area = 1922
max area = 1819
max area = 1919
max area = 1913
max area = 1953
max area = 1956
max area = 2041
max area = 1992
max area = 1874
max area = 1720
max area = 1622
max area = 1676
max area = 1717
max area = 1507
max area = 1685
max area = 1793
max area = 1981
max area = 1862
max area = 1959
max area = 1955
max area = 1971
max area = 1898
max area = 1953
max area = 1896
max area = 1864
max

In [27]:
#Define precision, recall and F1-score

#Define global TP TN, FP, FN
TP , TN , FP , FN = 0 , 0 , 0 , 0
import cv2
import numpy as np

path = 'mats/pedestrian/pedestrian/input'
path_gt = 'mats/pedestrian/pedestrian/groundtruth'
prev_frame = cv2.cvtColor(cv2.imread ( f'{path}/in000300.jpg ' ), cv2.COLOR_BGR2GRAY)
with open ( f'mats/pedestrian/pedestrian/temporalROI.txt ' , 'r' ) as f:
  line = f.readline()
  a,b = line.split()
  roi_start = int(a)
  roi_end = int(b)

results_pedestrian = ''

for i in range (roi_start ,roi_end):
  I=cv2.imread ( f'{path}/in%06d.jpg ' % i )
  I_GT=cv2.imread ( f'{path_gt}/gt%06d.png ' % i )

  gray = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)
  diff = cv2.absdiff(gray, prev_frame)
  T,binarized = cv2.threshold(diff, 7, 255, cv2.THRESH_BINARY)
  
  median = cv2.medianBlur(binarized, 5)
  kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (2,2))

  eroded = cv2.erode(median, kernel, iterations=1)
  dilated = cv2.dilate(eroded, kernel, iterations=1)

  retval , labels , stats , centroids = cv2.connectedComponentsWithStats(dilated)

  # cv2.imshow ( " dilated " ,np.uint8(labels * 255 / retval) )

  I_VIS = I.copy()
  if(stats.shape[0]>1):
    tab = stats[1:,4]
    pi = np.argmax(tab)
    # print(f'max area = {tab[pi]}')

    if (tab[pi]>500):
      pi = pi + 1
      cv2.rectangle(I_VIS, (stats[pi,0],stats[pi,1]), (stats[pi,0]+stats[pi,2],stats[pi,1]+stats[pi,3]), (255,0,0), 2)
      cv2.putText(I_VIS, "%f" %stats[pi,4],(stats[pi,0],stats[pi,1]),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,0,0))


      TP_M = np.logical_and((dilated == 255), (I_GT[:,:,0] == 255))
      TP_S = np . sum ( TP_M )
      TP = TP + TP_S

      FP_M = np.logical_and((dilated == 255), (I_GT[:,:,0] == 0))
      FP_S = np . sum ( FP_M )
      FP = FP + FP_S

      FN_M = np.logical_and((dilated == 0), (I_GT[:,:,0] == 255))
      FN_S = np . sum ( FN_M )
      FN = FN + FN_S

      TN_M = np.logical_and((dilated == 0), (I_GT[:,:,0] == 0))
      TN_S = np . sum ( TN_M )
      TN = TN + TN_S

      if TP + FP != 0:
        precision = TP / (TP + FP)
      else:
        precision = 0
      if TP + FN != 0:
        recall = TP / (TP + FN)
      else:
        recall = 0
      if precision + recall != 0:
        F1 = 2 * precision * recall / (precision + recall)
      else:
        F1 = 0
    else:
      precision = 0
      recall = 0
      F1 = 0
  else:
    precision = 0
    recall = 0
    F1 = 0

  print(f'precision = {precision} recall = {recall} F1 = {F1}')

  # add to results_pedestrian json
  results_pedestrian = results_pedestrian + f'{{"frame": {i}, "precision": {precision:.2f}, "recall": {recall:.2f}, "F1": {F1:.2f}}},'
  cv2.imshow ( " I_VIS " ,I_VIS )
  cv2.waitKey(10)
  prev_frame = gray
  
cv2.destroyAllWindows()

import json
with open('results_pedestrian.json', 'w') as f:
  json.dump(results_pedestrian, f)

precision = 0 recall = 0 F1 = 0
precision = 0 recall = 0 F1 = 0
precision = 0 recall = 0 F1 = 0
precision = 0 recall = 0 F1 = 0
precision = 0 recall = 0 F1 = 0
precision = 0 recall = 0 F1 = 0
precision = 0 recall = 0 F1 = 0
precision = 0.4085603112840467 recall = 1.0 F1 = 0.5801104972375691
precision = 0.5120296113510179 recall = 0.9799291617473436 F1 = 0.6726094003241492
precision = 0.5422254440014498 recall = 0.951048951048951 F1 = 0.6906740535549399
precision = 0.5767314399601395 recall = 0.9593866556154165 F1 = 0.720398319589233
precision = 0.6150855365474339 recall = 0.9556025369978859 F1 = 0.7484328799526908
precision = 0.6307124172949684 recall = 0.9545877969259432 F1 = 0.7595663856203095
precision = 0.6461441213653603 recall = 0.9567577686259828 F1 = 0.7713552671294899
precision = 0.6457408363448632 recall = 0.9596440079791315 F1 = 0.772003456363412
precision = 0.6576919670534054 recall = 0.9570820982085321 F1 = 0.7796325459317586
precision = 0.6671111459722331 recall = 0.95294

In [31]:
# For highway dataset
TP , TN , FP , FN = 0 , 0 , 0 , 0
import cv2
import numpy as np

path = 'mats/highway/highway/input'
path_gt = 'mats/highway/highway/groundtruth'
with open ( f'mats/highway/highway/temporalROI.txt ' , 'r' ) as f:
  line = f.readline()
  a,b = line.split()
  roi_start = int(a)
  roi_end = int(b)

results_highway = ''

prev_frame = cv2.cvtColor(cv2.imread ( f'{path}/in%06d.jpg '% roi_start ), cv2.COLOR_BGR2GRAY)

for i in range (roi_start ,roi_end):
  I=cv2.imread ( f'{path}/in%06d.jpg ' % i )
  I_GT=cv2.imread ( f'{path_gt}/gt%06d.png ' % i )

  gray = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)
  diff = cv2.absdiff(gray, prev_frame)
  T,binarized = cv2.threshold(diff, 10, 255, cv2.THRESH_BINARY)
  
  median = cv2.medianBlur(binarized, 5)
  kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (2,2))

  eroded = cv2.erode(median, kernel, iterations=1)
  dilated = cv2.dilate(eroded, kernel, iterations=1)

  retval , labels , stats , centroids = cv2.connectedComponentsWithStats(dilated)

  # cv2.imshow ( " dilated " ,np.uint8(labels * 255 / retval) )

  I_VIS = I.copy()
  if(stats.shape[0]>1):
    tab = stats[1:,4]
    pi = np.argmax(tab)
    # print(f'max area = {tab[pi]}')

    if (tab[pi]>300):
      pi = pi + 1
      cv2.rectangle(I_VIS, (stats[pi,0],stats[pi,1]), (stats[pi,0]+stats[pi,2],stats[pi,1]+stats[pi,3]), (255,0,0), 2)
      cv2.putText(I_VIS, "%f" %stats[pi,4],(stats[pi,0],stats[pi,1]),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,0,0))


  TP_M = np.logical_and((dilated == 255), (I_GT[:,:,0] == 255))
  TP_S = np . sum ( TP_M )
  TP = TP + TP_S

  FP_M = np.logical_and((dilated == 255), (I_GT[:,:,0] == 0))
  FP_S = np . sum ( FP_M )
  FP = FP + FP_S

  FN_M = np.logical_and((dilated == 0), (I_GT[:,:,0] == 255))
  FN_S = np . sum ( FN_M )
  FN = FN + FN_S

  TN_M = np.logical_and((dilated == 0), (I_GT[:,:,0] == 0))
  TN_S = np . sum ( TN_M )
  TN = TN + TN_S

  if TP + FP != 0:
    precision = TP / (TP + FP)
  else:
    precision = 0
  if TP + FN != 0:
    recall = TP / (TP + FN)
  else:
    recall = 0
  if precision + recall != 0:
    F1 = 2 * precision * recall / (precision + recall)
  else:
    F1 = 0

  print(f'precision = {precision} recall = {recall} F1 = {F1}')

  # add to results_pedestrian json
  results_highway = results_pedestrian + f'{{"frame": {i}, "precision": {precision:.2f}, "recall": {recall:.2f}, "F1": {F1:.2f}}},'
  cv2.imshow ( " I_VIS " ,I_VIS )
  cv2.waitKey(10)
  prev_frame = gray
  
cv2.destroyAllWindows()

import json
with open('results_highway.json', 'w') as f:
  json.dump(results_highway, f)

precision = 0 recall = 0.0 F1 = 0


precision = 0.3333333333333333 recall = 0.13095238095238096 F1 = 0.188034188034188
precision = 0.24444444444444444 recall = 0.12087912087912088 F1 = 0.16176470588235295
precision = 0.205607476635514 recall = 0.1134020618556701 F1 = 0.14617940199335547
precision = 0.22072072072072071 recall = 0.11556603773584906 F1 = 0.15170278637770898
precision = 0.2551440329218107 recall = 0.13247863247863248 F1 = 0.17440225035161744
precision = 0.2391304347826087 recall = 0.12815533980582525 F1 = 0.16687737041719344
precision = 0.22356495468277945 recall = 0.1284722222222222 F1 = 0.1631753031973539
precision = 0.19794344473007713 recall = 0.12050078247261346 F1 = 0.14980544747081712
precision = 0.17920353982300885 recall = 0.11587982832618025 F1 = 0.14074717636837533
precision = 0.18979591836734694 recall = 0.12093628088426528 F1 = 0.14773629864972201
precision = 0.2125 recall = 0.13837209302325582 F1 = 0.1676056338028169
precision = 0.21686746987951808 recall = 0.13263157894736843 F1 = 0.1645983017

In [39]:
# For office dataset
TP , TN , FP , FN = 0 , 0 , 0 , 0
import cv2
import numpy as np

path = 'mats/office/office/input'
path_gt = 'mats/office/office/groundtruth'
prev_frame = cv2.cvtColor(cv2.imread ( f'{path}/in000300.jpg ' ), cv2.COLOR_BGR2GRAY)
with open ( f'mats/office/office/temporalROI.txt ' , 'r' ) as f:
  line = f.readline()
  a,b = line.split()
  roi_start = int(a)
  roi_end = int(b)

results_office = ''

for i in range (roi_start ,roi_end):
  I=cv2.imread ( f'{path}/in%06d.jpg ' % i )
  I_GT=cv2.imread ( f'{path_gt}/gt%06d.png ' % i )

  gray = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)
  diff = cv2.absdiff(gray, prev_frame)
  T,binarized = cv2.threshold(diff, 5, 255, cv2.THRESH_BINARY)
  
  median = cv2.medianBlur(binarized, 5)
  kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (4,4))

  eroded = cv2.erode(median, kernel, iterations=1)
  dilated = cv2.dilate(eroded, kernel, iterations=1)


  for _ in range(10):
    dilated = cv2.dilate(eroded, kernel, iterations=1)
    eroded = cv2.erode(dilated, kernel, iterations=1)


  retval , labels , stats , centroids = cv2.connectedComponentsWithStats(dilated)

  # cv2.imshow ( " dilated " ,np.uint8(labels * 255 / retval) )

  I_VIS = I.copy()
  if(stats.shape[0]>1):
    tab = stats[1:,4]
    pi = np.argmax(tab)
    # print(f'max area = {tab[pi]}')

    if (tab[pi]>500):
      pi = pi + 1
      cv2.rectangle(I_VIS, (stats[pi,0],stats[pi,1]), (stats[pi,0]+stats[pi,2],stats[pi,1]+stats[pi,3]), (255,0,0), 2)
      cv2.putText(I_VIS, "%f" %stats[pi,4],(stats[pi,0],stats[pi,1]),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,0,0))


  TP_M = np.logical_and((dilated == 255), (I_GT[:,:,0] == 255))
  TP_S = np . sum ( TP_M )
  TP = TP + TP_S

  FP_M = np.logical_and((dilated == 255), (I_GT[:,:,0] == 0))
  FP_S = np . sum ( FP_M )
  FP = FP + FP_S

  FN_M = np.logical_and((dilated == 0), (I_GT[:,:,0] == 255))
  FN_S = np . sum ( FN_M )
  FN = FN + FN_S

  TN_M = np.logical_and((dilated == 0), (I_GT[:,:,0] == 0))
  TN_S = np . sum ( TN_M )
  TN = TN + TN_S

  if TP + FP != 0:
    precision = TP / (TP + FP)
  else:
    precision = 0
  if TP + FN != 0:
    recall = TP / (TP + FN)
  else:
    recall = 0
  if precision + recall != 0:
    F1 = 2 * precision * recall / (precision + recall)
  else:
    F1 = 0

  print(f'precision = {precision} recall = {recall} F1 = {F1}')

  # add to results_pedestrian json
  results_office = results_office + f'{{"frame": {i}, "precision": {precision:.2f}, "recall": {recall:.2f}, "F1": {F1:.2f}}},'
  cv2.imshow ( " I_VIS " ,I_VIS )
  cv2.waitKey(10)
  prev_frame = gray
  
cv2.destroyAllWindows()

import json
with open('results_office.json', 'w') as f:
  json.dump(results_office, f)

precision = 0.0 recall = 0 F1 = 0
precision = 0.0 recall = 0 F1 = 0
precision = 0.0 recall = 0 F1 = 0
precision = 0.0 recall = 0 F1 = 0
precision = 0.0 recall = 0 F1 = 0
precision = 0.0 recall = 0 F1 = 0
precision = 0.0 recall = 0 F1 = 0
precision = 0.0 recall = 0 F1 = 0
precision = 0.0 recall = 0 F1 = 0
precision = 0.0 recall = 0 F1 = 0
precision = 0.0 recall = 0 F1 = 0
precision = 0.0 recall = 0 F1 = 0
precision = 0.0 recall = 0.0 F1 = 0
precision = 0.0 recall = 0.0 F1 = 0
precision = 0.00039099155458242104 recall = 0.05555555555555555 F1 = 0.000776518092871564
precision = 0.0019459459459459458 recall = 0.1330049261083744 F1 = 0.003835772126722546
precision = 0.0029962048072441575 recall = 0.1174934725848564 F1 = 0.00584339696143358
precision = 0.004816665663194653 recall = 0.121765601217656 F1 = 0.009266767056643112
precision = 0.007222586999343401 recall = 0.12643678160919541 F1 = 0.013664596273291925
precision = 0.011429997504367358 recall = 0.14521242866201647 F1 = 0.021191930409

KeyboardInterrupt: 

: 

In [33]:
### Modify highway to detect all the vehicles

# For highway dataset
TP , TN , FP , FN = 0 , 0 , 0 , 0
import cv2
import numpy as np

path = 'mats/highway/highway/input'
path_gt = 'mats/highway/highway/groundtruth'
prev_frame = cv2.cvtColor(cv2.imread ( f'{path}/in000300.jpg ' ), cv2.COLOR_BGR2GRAY)
with open ( f'mats/highway/highway/temporalROI.txt ' , 'r' ) as f:
  line = f.readline()
  a,b = line.split()
  roi_start = int(a)
  roi_end = int(b)

results_highway = ''

for i in range (roi_start ,roi_end):
  I=cv2.imread ( f'{path}/in%06d.jpg ' % i )
  I_GT=cv2.imread ( f'{path_gt}/gt%06d.png ' % i )

  gray = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)
  diff = cv2.absdiff(gray, prev_frame)
  T,binarized = cv2.threshold(diff, 10, 255, cv2.THRESH_BINARY)
  
  median = cv2.medianBlur(binarized, 5)
  kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3,3))

  eroded = cv2.erode(median, kernel, iterations=1)
  dilated = cv2.dilate(eroded, kernel, iterations=1)

  retval , labels , stats , centroids = cv2.connectedComponentsWithStats(dilated)

  # cv2.imshow ( " dilated " ,np.uint8(labels * 255 / retval) )

  I_VIS = I.copy()
  if(stats.shape[0]>1):
    tab = stats[1:,4]
    pi = np.argmax(tab)

    for pi in range(1, stats.shape[0]):
        if (stats[pi,4]>300):
            cv2.rectangle(I_VIS, (stats[pi,0],stats[pi,1]), (stats[pi,0]+stats[pi,2],stats[pi,1]+stats[pi,3]), (255,0,0), 2)
            cv2.putText(I_VIS, "%f" %stats[pi,4],(stats[pi,0],stats[pi,1]),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,0,0))



  TP_M = np.logical_and((dilated == 255), (I_GT[:,:,0] == 255))
  TP_S = np . sum ( TP_M )
  TP = TP + TP_S

  FP_M = np.logical_and((dilated == 255), (I_GT[:,:,0] == 0))
  FP_S = np . sum ( FP_M )
  FP = FP + FP_S

  FN_M = np.logical_and((dilated == 0), (I_GT[:,:,0] == 255))
  FN_S = np . sum ( FN_M )
  FN = FN + FN_S

  TN_M = np.logical_and((dilated == 0), (I_GT[:,:,0] == 0))
  TN_S = np . sum ( TN_M )
  TN = TN + TN_S

  if TP + FP != 0:
    precision = TP / (TP + FP)
  else:
    precision = 0
  if TP + FN != 0:
    recall = TP / (TP + FN)
  else:
    recall = 0
  if precision + recall != 0:
    F1 = 2 * precision * recall / (precision + recall)
  else:
    F1 = 0

  print(f'precision = {precision} recall = {recall} F1 = {F1}')

  # add to results_pedestrian json
  results_highway = results_pedestrian + f'{{"frame": {i}, "precision": {precision:.2f}, "recall": {recall:.2f}, "F1": {F1:.2f}}},'
  cv2.imshow ( " I_VIS " ,I_VIS )
  cv2.waitKey(10)
  prev_frame = gray
  
cv2.destroyAllWindows()

import json
with open('results_highway.json', 'w') as f:
  json.dump(results_highway, f)

precision = 0.005873976504093984 recall = 1.0 F1 = 0.011679348787825164
precision = 0.006830025501718594 recall = 0.9166666666666666 F1 = 0.01355902357421144
precision = 0.006825031022868286 recall = 0.8461538461538461 F1 = 0.013540842345906972
precision = 0.006823216659282233 recall = 0.7938144329896907 F1 = 0.013530135301353014
precision = 0.006998272578287638 recall = 0.7452830188679245 F1 = 0.013866339023212954
precision = 0.007042253521126761 recall = 0.6794871794871795 F1 = 0.013940031562335614
precision = 0.007106801275239107 recall = 0.6233009708737864 F1 = 0.014053367773570037
precision = 0.007123421011879742 recall = 0.5590277777777778 F1 = 0.014067585574171563
precision = 0.0071625953354703216 recall = 0.5070422535211268 F1 = 0.014125648515498974
precision = 0.007222369467267426 recall = 0.4678111587982833 F1 = 0.014225122349102772
precision = 0.007353915463097919 recall = 0.43302990897269183 F1 = 0.014462226661744586
precision = 0.007855078219809802 recall = 0.4139534883720

In [1]:
### Modify highway to detect all the vehicles

# For highway dataset
global TP , TN , FP , FN
import cv2
import numpy as np


def analyse_video(_name, mask_size, threshold, erosion, dilation, min_area):
    TP , TN , FP , FN = 0 , 0 , 0 , 0
    path = f'mats/{_name}/{_name}/input'
    path_gt = f'mats/{_name}/{_name}/groundtruth'
    with open ( f'mats/{_name}/{_name}/temporalROI.txt ' , 'r' ) as f:
        line = f.readline()
        a,b = line.split()
        roi_start = int(a)
        roi_end = int(b)

    prev_frame = cv2.cvtColor(cv2.imread ( f'{path}/in%06d.jpg '% roi_start ), cv2.COLOR_BGR2GRAY)

    results = ''

    for i in range (roi_start ,roi_end):
        I=cv2.imread ( f'{path}/in%06d.jpg ' % i )
        I_GT=cv2.imread ( f'{path_gt}/gt%06d.png ' % i )
        # print(f'frame {i}, I = {I.shape}, I_GT = {I_GT.shape}')
        gray = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)
        diff = cv2.absdiff(gray, prev_frame)
        T,binarized = cv2.threshold(diff, threshold, 255, cv2.THRESH_BINARY)
        
        median = cv2.medianBlur(binarized, 5)
        kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (mask_size, mask_size))

        eroded = cv2.erode(median, kernel, iterations=1)
        dilated = cv2.dilate(eroded, kernel, iterations=1)

        retval , labels , stats , centroids = cv2.connectedComponentsWithStats(dilated)

        # cv2.imshow ( " dilated " ,np.uint8(labels * 255 / retval) )

        I_VIS = I.copy()
        if(stats.shape[0]>1):
            tab = stats[1:,4]
            pi = np.argmax(tab)

            for pi in range(1, stats.shape[0]):
                if (stats[pi,4]>min_area):
                    cv2.rectangle(I_VIS, (stats[pi,0],stats[pi,1]), (stats[pi,0]+stats[pi,2],stats[pi,1]+stats[pi,3]), (255,0,0), 2)
                    cv2.putText(I_VIS, "%f" %stats[pi,4],(stats[pi,0],stats[pi,1]),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,0,0))



                    TP_M = np.logical_and((dilated == 255), (I_GT[:,:,0] == 255))
                    TP_S = np . sum ( TP_M )
                    TP = TP + TP_S

                    FP_M = np.logical_and((dilated == 255), (I_GT[:,:,0] == 0))
                    FP_S = np . sum ( FP_M )
                    FP = FP + FP_S

                    FN_M = np.logical_and((dilated == 0), (I_GT[:,:,0] == 255))
                    FN_S = np . sum ( FN_M )
                    FN = FN + FN_S

                    TN_M = np.logical_and((dilated == 0), (I_GT[:,:,0] == 0))
                    TN_S = np . sum ( TN_M )
                    TN = TN + TN_S

                    if TP + FP != 0:
                        precision = TP / (TP + FP)
                    else:
                        precision = 0
                    if TP + FN != 0:
                        recall = TP / (TP + FN)
                    else:
                        recall = 0
                    if precision + recall != 0:
                        F1 = 2 * precision * recall / (precision + recall)
                    else:
                        F1 = 0
                else:
                    precision = 0
                    recall = 0
                    F1 = 0
            else:
                precision = 0
                recall = 0
                F1 = 0

        # print(f'precision = {precision} recall = {recall} F1 = {F1}')

        # add to results_pedestrian json
        # results = results + f'{{"frame": {i}, "precision": {precision:.2f}, "recall": {recall:.2f}, "F1": {F1:.2f}}},'
        cv2.imshow ( " I_VIS " ,I_VIS )
        cv2.waitKey(10)
        prev_frame = gray
    
    cv2.destroyAllWindows()

    precision = TP / (TP + FP)
    recall = TP / (TP + FN)
    F1 = 2 * precision * recall / (precision + recall)
    print(f'precision = {precision} recall = {recall} F1 = {F1}')
    
    import json
    with open('results_{_name}.json', 'w') as f:
        json.dump(results, f)

In [2]:
analyse_video('highway', 3, 10, 1, 1, 300)

precision = 0.9378033500983373 recall = 0.6935461669602411 F1 = 0.797388802365177


In [15]:
analyse_video('pedestrian', 2, 9, 1, 1, 400)

precision = 0.5862951986467477 recall = 0.7134964117601666 F1 = 0.6436716733934127


In [11]:
import cv2
import numpy as np

path = 'mats/bad_apple_is/input_2'
roi_start = 1
roi_end = 657

prev_frame = cv2.cvtColor(cv2.imread ( f'{path}/bad_apple_%04d.png '% roi_start ), cv2.COLOR_BGR2GRAY)

for i in range (roi_start ,roi_end):
  I=cv2.imread ( f'{path}/bad_apple_%04d.png ' % i )
  print ( " I = " ,I )
  cv2.imshow ( " I " ,I )

  # gray = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)
  # print(f'i = {i}, gray = {gray.shape}, prev_frame = {prev_frame.shape}')
  # diff = cv2.absdiff(gray, prev_frame)
  # T,binarized = cv2.threshold(diff, 10, 255, cv2.THRESH_BINARY)
  
  # median = cv2.medianBlur(binarized, 5)
  # kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (2,2))

  # eroded = cv2.erode(median, kernel, iterations=1)
  # dilated = cv2.dilate(eroded, kernel, iterations=1)

  # retval , labels , stats , centroids = cv2.connectedComponentsWithStats(dilated)

  # # cv2.imshow ( " dilated " ,np.uint8(labels * 255 / retval) )

  # I_VIS = I.copy()
  # if(stats.shape[0]>1):
  #   tab = stats[1:,4]
  #   pi = np.argmax(tab)
  #   # print(f'max area = {tab[pi]}')

  #   if (tab[pi]>300):
  #     pi = pi + 1
  #     cv2.rectangle(I_VIS, (stats[pi,0],stats[pi,1]), (stats[pi,0]+stats[pi,2],stats[pi,1]+stats[pi,3]), (255,0,0), 2)
  #     cv2.putText(I_VIS, "%f" %stats[pi,4],(stats[pi,0],stats[pi,1]),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,0,0))


  # cv2.imshow ( " I_VIS " ,I_VIS )
  # cv2.waitKey(10)
  # prev_frame = gray
  
cv2.destroyAllWindows()


 I =  [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
 I =  [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
 I =  [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0

In [31]:
path = 'mats/bad_apple_is/input'

#rename all frames from 001 to 999 to 0001 to 0999

import os

for i in range(1, 1000):
    os.rename(f'{path}/bad_apple_%03d.png' % i, f'{path}/bad_apple_%04d.png' % i)
    print(f'renamed {path}/bad_apple_%03d.png' % i)

renamed mats/bad_apple_is/input/bad_apple_001.png
renamed mats/bad_apple_is/input/bad_apple_002.png
renamed mats/bad_apple_is/input/bad_apple_003.png
renamed mats/bad_apple_is/input/bad_apple_004.png
renamed mats/bad_apple_is/input/bad_apple_005.png
renamed mats/bad_apple_is/input/bad_apple_006.png
renamed mats/bad_apple_is/input/bad_apple_007.png
renamed mats/bad_apple_is/input/bad_apple_008.png
renamed mats/bad_apple_is/input/bad_apple_009.png
renamed mats/bad_apple_is/input/bad_apple_010.png
renamed mats/bad_apple_is/input/bad_apple_011.png
renamed mats/bad_apple_is/input/bad_apple_012.png
renamed mats/bad_apple_is/input/bad_apple_013.png
renamed mats/bad_apple_is/input/bad_apple_014.png
renamed mats/bad_apple_is/input/bad_apple_015.png
renamed mats/bad_apple_is/input/bad_apple_016.png
renamed mats/bad_apple_is/input/bad_apple_017.png
renamed mats/bad_apple_is/input/bad_apple_018.png
renamed mats/bad_apple_is/input/bad_apple_019.png
renamed mats/bad_apple_is/input/bad_apple_020.png


In [7]:
path_1 = 'mats/bad_apple_is/input'

import os
import cv2

# os.mkdir('mats/bad_apple_is/input_2')

for i in range(1,6563):
    image = cv2.imread(f'{path_1}/bad_apple_%04d.png' % i)
    image = cv2.resize(image, (1280, 720))
    cv2.imwrite(f'mats/bad_apple_is/input_2/bad_apple_%04d.png' % i, image)


In [2]:
path = 'mats/bad_apple_is/input_2'
import matplotlib.pyplot as plt
import cv2
import numpy as np

# I = cv2.imread ( f'{path}/bad_apple_0100.png ' )
# plt.imshow(I)
prev_frame = cv2.cvtColor(cv2.imread ( f'{path}/bad_apple_0001.png ' ), cv2.COLOR_BGR2GRAY)
for i in range(1, 1000,2):
    I = cv2.imread ( f'{path}/bad_apple_%04d.png ' % i )
    I_gray = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)
    diff = cv2.absdiff(I_gray, prev_frame)
    T,binarized = cv2.threshold(diff, 10, 255, cv2.THRESH_BINARY)
    median = cv2.medianBlur(binarized, 5)
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5,5))

    eroded = cv2.erode(median, kernel, iterations=1)
    dilated = cv2.dilate(eroded, kernel, iterations=1)

    dilated = cv2.dilate(dilated, kernel, iterations=1)
    eroded = cv2.erode(dilated, kernel, iterations=1)

    retval, labels, stats, centroids = cv2.connectedComponentsWithStats(dilated)

    I_VIS = I.copy()

    if(stats.shape[0]>1):
        tab = stats[1:,4]
        pi = np.argmax(tab)

        for pi in range(1, stats.shape[0]):
            if (stats[pi,4]>1000):
                cv2.rectangle(I_VIS, (stats[pi,0],stats[pi,1]), (stats[pi,0]+stats[pi,2],stats[pi,1]+stats[pi,3]), (255,0,0), 2)
                cv2.putText(I_VIS, "%f" %stats[pi,4],(stats[pi,0],stats[pi,1]),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,0,0))

    cv2.imshow ( " I_VIS " ,I_VIS )

    cv2.waitKey(10)

cv2.destroyAllWindows()